name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # 🔥 Clean old builds
      - name: Clean
        run: |
          rm -rf .buildozer
          rm -rf bin
          rm -rf $HOME/android-sdk

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk wget curl

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.33

      # 🚀 Install Android SDK manually
      - name: Setup Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d $HOME/android-sdk/cmdline-tools

          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

          yes | sdkmanager --licenses

          # 🔥 ONLY stable tools install
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # 🔥 Link SDK to Buildozer (IMPORTANT)
      - name: Link SDK
        run: |
          mkdir -p .buildozer/android/platform
          ln -s $HOME/android-sdk .buildozer/android/platform/android-sdk

      # 🔥 Remove RC versions (CRITICAL FIX)
      - name: Remove RC build-tools
        run: |
          rm -rf $HOME/android-sdk/build-tools/37*

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

          # 🔥 FORCE correct version
          export BUILDOZER_BUILD_TOOLS_VERSION=33.0.2
          export ANDROIDAPI=33
          export ANDROIDMINAPI=21

          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
