name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk wget curl

      - name: Install Buildozer
        run: |
          pip install buildozer cython

      - name: Clean previous build
        run: rm -rf .buildozer

      - name: Setup Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          unzip tools.zip -d $HOME/android-sdk/cmdline-tools/tmp
          mv $HOME/android-sdk/cmdline-tools/tmp/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools

          export BUILDOZER_BUILD_TOOLS_VERSION=33.0.2
          export ANDROIDSDK_BUILD_TOOLS_VERSION=33.0.2

          buildozer android clean
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
